### PR TITLE
Fixes wrong constant for stopForeground method

### LINKED ISSUE #1199: Android build error Wrong Constant
## 🐛 Bug Report

Android gradle build error with message - 

```
 C:\flutter\.pub-cache\hosted\pub.dartlang.org\geolocator_android-4.1.4\android\src\main\java\com\baseflow\geolocator\GeolocatorLocationService.java:159: Error: Must be one of: Service.STOP_FOREGROUND_LEGACY, Service.STOP_FOREGROUND_REMOVE, Service.STOP_FOREGROUND_DETACH [WrongConstant]
          stopForeground(ONGOING_NOTIFICATION_ID);

 Explanation for issues of type "WrongConstant":
     Ensures that when parameter in a method only allows a specific set of
     constants, calls obey those rules.
```

### Expected behavior
Should be able to build in android

### Reproduction steps
cd to android
run .\gradlew build

### Configuration

**Version:** 9.0.2

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android

### PR DESCRIPTION
**Pull request by mvanbeusekom**
Fixes an issue where the wrong constant is supplied to the `stopForeground` method (see [documentation](https://developer.android.com/reference/android/app/Service#stopForeground(int))).

This PR also addresses some deprecation warnings that showed up when running Android lint against `compileSdkVersion 33`.

Resolves #1199 

## Pre-launch Checklist

- [x] I made sure the project builds.
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is does not need version changes.
- [x] I updated `CHANGELOG.md` to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I rebased onto `main`.
- [x] I added new tests to check the change I am making, or this PR does not need tests.
- [x] I made sure all existing and new tests are passing.
- [x] I ran `dart format .` and committed any changes.
- [x] I ran `flutter analyze` and fixed any errors.

[Contributor Guide]: https://github.com/Baseflow/flutter-geolocator/blob/master/CONTRIBUTING.md
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

File: geolocator_android/android/src/main/java/com/baseflow/geolocator/location/FusedLocationClient.java [hunk 1]
```diff
@@ -83,6 +84,24 @@ public synchronized void onLocationAvailability(
...
+    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.TIRAMISU) {
+      return buildLocationRequestDeprecated(options);
+    }
+
+    LocationRequest.Builder builder = new LocationRequest.Builder(0);
+
+    if (options != null) {
+      builder.setPriority(toPriority(options.getAccuracy()));
+      builder.setIntervalMillis(options.getTimeInterval());
+      builder.setMinUpdateIntervalMillis(options.getTimeInterval());
```
Comment (TimHoogstrate) [inline geolocator_android/android/src/main/java/com/baseflow/geolocator/location/FusedLocationClient.java:96]: Elsewhere we use: setFastestInterval(options.getTimeInterval() / 2), should we bring this in line?

**Review by TimHoogstrate — APPROVED** [review]
