### PR TITLE
fix: Android API 33 deprecation issues

### LINKED ISSUE #1084: Android: the build fails with compileSdkVersion 33
## 🐛 Bug Report

I have to bump compileSdkVersion to 33 because of dependencies on other packages. Compilation fails:

/dev/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator_android-3.2.1/android/src/main/java/com/baseflow/geolocator/GeolocatorLocationService.java:134: warning: [deprecation] stopForeground(boolean) in Service has been deprecated
      stopForeground(true);
      ^
error: warnings found and -Werror specified
/dev/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator_android-3.2.1/android/src/main/java/com/baseflow/geolocator/permission/PermissionUtils.java:27: warning: [deprecation] getPackageInfo(String,int) in PackageManager has been deprecated
              .getPackageInfo(context.getPackageName(), PackageManager.GET_PERMISSIONS);
              ^
1 error
2 warnings

FAILURE: Build failed with an exception.

### Expected behavior

Compilation succeeds.

### Reproduction steps

add compileSdkVersion 33 to build.gradle, try to build

### Configuration

**Version:** 8.2.1

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

### PR DESCRIPTION
**Pull request by Wendler**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Bug fix

### :arrow_heading_down: What is the current behavior?
The build fails with `compileSdkVersion 33`

### :new: What is the new behavior (if this is a feature change)?
Compilation succeeds without deprecation warnings.

### :boom: Does this PR introduce a breaking change?
Yes
`compileSdkVersion` >= `33`

### :bug: Recommendations for testing
Run the example App on Android 13 and look for deprecation warnings.

### :memo: Links to relevant issues/docs
Closes #1084

### :thinking: Checklist before submitting

- [x] I made sure all projects build.
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning).
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I followed the style guide lines ([code style guide](https://github.com/Baseflow/flutter-geolocator/blob/master/CONTRIBUTING.md)).
- [x] I updated the relevant documentation.
- [x] I rebased onto current `master`.

### CODE REVIEW

File: geolocator_android/android/src/main/java/com/baseflow/geolocator/permission/PermissionUtils.java [hunk 1]
```diff
@@ -38,4 +34,17 @@ public static boolean hasPermissionInManifest(Context context, String permission
...
+    final String packageName = context.getPackageName();
+
+    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
+      return packageManager.getPackageInfo(packageName,
+          PackageManager.PackageInfoFlags.of(PackageManager.GET_PERMISSIONS));
+    }
+
+    return packageManager.getPackageInfo(packageName, PackageManager.GET_PERMISSIONS);
+  }
+}
```
Comment (mvanbeusekom) [inline geolocator_android/android/src/main/java/com/baseflow/geolocator/permission/PermissionUtils.java:50]: nit: missing line break. To comply to POSIX format each file needs to end with an empty line. This ensures all IDEs work correctly (although most modern IDEs don't care, it is still preferable to end the file with an empty line).

**Review by mvanbeusekom — CHANGES_REQUESTED** [review]
Thank you for this PR looks very promising, just two little remarks which would be awesome if you could fix those.

File: geolocator_android/android/src/main/java/com/baseflow/geolocator/permission/PermissionUtils.java [hunk 2]
```diff
@@ -38,4 +34,17 @@ public static boolean hasPermissionInManifest(Context context, String permission
...
+  private static PackageInfo getPackageInfo(Context context) throws PackageManager.NameNotFoundException {
+    final PackageManager packageManager = context.getPackageManager();
+    final String packageName = context.getPackageName();
+
+    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
+      return packageManager.getPackageInfo(packageName,
+          PackageManager.PackageInfoFlags.of(PackageManager.GET_PERMISSIONS));
+    }
+
+    return packageManager.getPackageInfo(packageName, PackageManager.GET_PERMISSIONS);
```
Comment (mvanbeusekom) [inline geolocator_android/android/src/main/java/com/baseflow/geolocator/permission/PermissionUtils.java:48]: Sorry about this, I forgot hitting the safe button with the earlier review. I meant to ask you to update t this statement so that the branched flow contains the deprecated code:

```suggestion
    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.TIRAMISU) {
      return packageManager.getPackageInfo(packageName, PackageManager.GET_PERMISSIONS);
    }
    
    return packageManager.getPackageInfo(packageName,
        PackageManager.PackageInfoFlags.of(PackageManager.GET_PERMISSIONS));
```

**Review by mvanbeusekom — CHANGES_REQUESTED** [review]

**Review by mvanbeusekom — APPROVED** [review]
LGTM, thank you very much for the contribution
