### PR TITLE
Cancel location stream on `getCurrentPosition` timeout

### LINKED ISSUE #1259: Can't turn off location updates
## 🐛 Bug Report

**Version:** 4.1.7

**Platform:** 
- [ ] :robot: Android

I think the plugin needs a function to stop positioning, in android plugin, in some cases, we need to stop positioning manually. 

For example, startPositionUpdates has not returned a result for a long time, or the positioning has timed out. At this time, we cannot close the positioning, which causes the positioning to be permanent and consumes power.

### PR DESCRIPTION
**Pull request by JeroenWeener**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
This PR fixes a bug where Android kept polling for a location after a request for the current location timed out.
Additionally, it enhances the `MethodChannelMock` class to cater to multiple mock methods.

### :arrow_heading_down: What is the current behavior?
Currently, when calling `getCurrentPosition()` with a provided `timeout`, the plugin will keep polling the gps on Android after the timeout, instead of cancelling the operation.

### :new: What is the new behavior (if this is a feature change)?
After a timeout, Android is instructed to stop polling the gps.

### :boom: Does this PR introduce a breaking change?
This PR does not introduce a breaking change.

### :bug: Recommendations for testing
The PR includes a test that checks whether the cancel request is fired after the request times out. The `MethodChannelMock` class was updated in the process.

### :memo: Links to relevant issues/docs
Closes #1259.

### :thinking: Checklist before submitting

- [x] I made sure all projects build.
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning).
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I followed the style guide lines ([code style guide](https://github.com/Baseflow/flutter-geolocator/blob/master/CONTRIBUTING.md)).
- [x] I updated the relevant documentation.
- [x] I rebased onto current `master`.

### CODE REVIEW

File: geolocator_android/android/src/main/java/com/baseflow/geolocator/MethodCallHandlerImpl.java [hunk 1]
```diff
@@ -210,14 +225,17 @@ private void onGetCurrentPosition(MethodCall call, MethodChannel.Result result)
...
     Map<String, Object> map = (Map<String, Object>) call.arguments;
     boolean forceLocationManager = false;
-    if (map != null && map.get("forceLocationManager") != null) {
+    if (map.get("forceLocationManager") != null) {
       forceLocationManager = (boolean) map.get("forceLocationManager");
     }
     LocationOptions locationOptions = LocationOptions.parseArguments(map);
+    String requestId = (String) map.get("requestId");
+
     final boolean[] replySubmitted = {false};
```
Comment (JeroenWeener) [inline geolocator_android/android/src/main/java/com/baseflow/geolocator/MethodCallHandlerImpl.java:234]: This is likely an array so the boolean can be passed by reference, rather than by value. However, that does not seem necessary here.

File: geolocator_android/android/src/main/java/com/baseflow/geolocator/MethodCallHandlerImpl.java [hunk 2]
```diff
@@ -238,7 +257,24 @@ private void onGetCurrentPosition(MethodCall call, MethodChannel.Result result)
...
+      @SuppressWarnings("unchecked")
+      Map<String, Object> arguments = (Map<String, Object>) call.arguments;
+      String requestId = (String) arguments.get("requestId");
+
+      LocationClient locationClient = this.pendingCurrentPositionLocationClients.get(requestId);
+      if (locationClient != null) {
+        locationClient.stopPositionUpdates();
+      }
+
+      result.success(null);
```
Comment (JeroenWeener) [inline geolocator_android/android/src/main/java/com/baseflow/geolocator/MethodCallHandlerImpl.java:278]: Fail silently or call `result.error()`?

File: geolocator_android/android/src/main/java/com/baseflow/geolocator/MethodCallHandlerImpl.java [hunk 3]
```diff
@@ -238,7 +258,25 @@ private void onGetCurrentPosition(MethodCall call, MethodChannel.Result result)
...
+    Map<String, Object> arguments = (Map<String, Object>) call.arguments;
+    String requestId = (String) arguments.get("requestId");
+
+    LocationClient locationClient = this.pendingCurrentPositionLocationClients.get(requestId);
+    if (locationClient != null) {
+      locationClient.stopPositionUpdates();
+    }
+    this.pendingCurrentPositionLocationClients.remove(requestId);
+
+    result.success(null);
```
Comment (JeroenWeener) [inline geolocator_android/android/src/main/java/com/baseflow/geolocator/MethodCallHandlerImpl.java:280]: Fail silently in case there is no location client for the request identifier, or call result.error()?

File: geolocator_android/android/src/main/java/com/baseflow/geolocator/location/LocationMapper.java [hunk 4]
```diff
@@ -6,7 +6,6 @@
 import java.util.HashMap;
 import java.util.Map;
 
-@SuppressWarnings("deprecation")
```
Comment (TimHoogstrate) [inline geolocator_android/android/src/main/java/com/baseflow/geolocator/location/LocationMapper.java:9]: Why is this un-deprecated? Or why was it deprecated? Any ideas?

Comment (JeroenWeener) [reply geolocator_android/android/src/main/java/com/baseflow/geolocator/location/LocationMapper.java:9]: VSCode indicated that this warning was redundant, so I removed it. I assumed that somewhere in a previous PR, a call to a deprecated method was removed/replaced, and the author forgot to remove this annotation.

File: geolocator_android/CHANGELOG.md [hunk 5]
```diff
@@ -1,3 +1,7 @@
+## 4.1.9
+
+* Fixes a bug where the location service would not stop correctly when the location stream timed out.
```
Comment (andreisas06) [inline geolocator_android/CHANGELOG.md:3]:
```suggestion
* Resolves an issue where the location service failed to stop properly upon timeout of the location stream.
```

File: geolocator_android/android/src/main/java/com/baseflow/geolocator/MethodCallHandlerImpl.java (hunk 3 above)
Comment (mvanbeusekom) [reply geolocator_android/android/src/main/java/com/baseflow/geolocator/MethodCallHandlerImpl.java:280]: In this case I think failing silently would be the right approach. It should never happen and if for some reason it does happen returning an error will only cause confusion to the consuming developer.

File: geolocator_android/android/src/main/java/com/baseflow/geolocator/MethodCallHandlerImpl.java (hunk 1 above)
Comment (JeroenWeener) [reply geolocator_android/android/src/main/java/com/baseflow/geolocator/MethodCallHandlerImpl.java:235]: Turns out we do need the array:

image

image

**Review by mvanbeusekom — APPROVED** [review]
LGTM!
